use qmake6 if others aren't available

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -540,7 +540,12 @@ if [ -z "$QTDIR" ]; then
         if [ $? -eq 0 ]; then
             QMAKE_BIN=`which qmake-qt5`
         else
-            echo "qmake was not found in your path\n"
+            which qmake6 > /dev/null
+            if [ $? -eq 0 ]; then
+                QMAKE_BIN=`which qmake6`
+            else
+                echo "qmake was not found in your path\n"
+            fi
         fi
     fi
 elif [ -f "$QTDIR/bin/qmake" ]; then
